version: "2.1"

services:

  php:
    build: ./Build/Docker/php-fpm
    image: "secret/php:7.1-fpm-alpine"
    links:
      - "mariadb"
    environment:
      FLOW_CONTEXT: "${FLOW_CONTEXT}"
    volumes:
      - "./Data:/data/"
    mem_limit: 128m
    restart: always

  nginx:
    build: ./Build/Docker/nginx
    image: "secret/nginx:1.11-alpine"
    command: /bin/sh -c "/data/Build/Docker/nginx/run_nginx.sh"
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    links:
      - "php"
    volumes:
      - "./Data:/data/"
    environment:
      FLOW_CONTEXT: "${FLOW_CONTEXT}"
      NGINX_PORT: "${NGINX_PORT}"
    mem_limit: 50m
    restart: always

  mariadb:
    build: ./Build/Docker/mariadb
    image: "secret/mariadb:10.1-debian-jessie"
    command: "--character-set-server=utf8 --collation-server=utf8_unicode_ci"
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    mem_limit: 128m
    restart: always