-
  name: '/'
  uriPattern: ''
  defaults:
    '@package': 'Egobude.SecretManagement'
    '@controller': 'Secret'
    '@action': 'index'

-
  name: 'Show a link'
  uriPattern: 'show/{linkToken}'
  defaults:
    '@package': 'Egobude.SecretManagement'
    '@controller': 'Secret'
    '@action': 'show'