<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20170629083442 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE egobude_secretmanagement_domain_model_secret ADD lifetime VARCHAR(255) NOT NULL, DROP description, DROP linktoken, DROP expirydate, DROP expired');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE egobude_secretmanagement_domain_model_secret ADD description LONGTEXT NOT NULL COLLATE utf8_unicode_ci, ADD linktoken LONGTEXT NOT NULL COLLATE utf8_unicode_ci, ADD expirydate DATETIME NOT NULL, ADD expired TINYINT(1) NOT NULL, DROP lifetime');
    }
}
