<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20170626062957 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('CREATE TABLE egobude_secretmanagement_domain_model_secretshare (persistence_object_identifier VARCHAR(40) NOT NULL, secret VARCHAR(40) DEFAULT NULL, emailaddress VARCHAR(255) NOT NULL, notified TINYINT(1) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_D9CE25635CA2E8E5 (secret), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE egobude_secretmanagement_domain_model_secret (persistence_object_identifier VARCHAR(40) NOT NULL, secret VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, linktoken VARCHAR(255) NOT NULL, expirydate DATETIME NOT NULL, expired TINYINT(1) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE egobude_secretmanagement_domain_model_secretshare ADD CONSTRAINT FK_D9CE25635CA2E8E5 FOREIGN KEY (secret) REFERENCES egobude_secretmanagement_domain_model_secret (persistence_object_identifier)');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE egobude_secretmanagement_domain_model_secretshare DROP FOREIGN KEY FK_D9CE25635CA2E8E5');
        $this->addSql('DROP TABLE egobude_secretmanagement_domain_model_secretshare');
        $this->addSql('DROP TABLE egobude_secretmanagement_domain_model_secret');
    }
}
